### ISSUE TITLE
Node stop working after update comfyui and the tripo node!

### ISSUE THREAD

**Issue by merecesarchviz** [VAST-AI-Research/ComfyUI-Tripo#29]
After update Comfyui for the last version and also the Comfyui Tripo extention to the last version when i run i got this error dont work anymore any idea what is?

# ComfyUI Error Report
## Error Details
- **Node Type:** TripoAPIDraft
- **Exception Type:** Exception
- **Exception Message:** An error occurred: 
## Stack Trace
```
  File "F:\Ai\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\Ai\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)

  File "F:\Ai\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)

  File "F:\Ai\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))

  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-Tripo\__init__.py", line 91, in generate_mesh
    result = api.image_to_3d(image_name, model_version, model_seed, texture_seed)

  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-Tripo\api\system.py", line 114, in image_to_3d
    return self._handle_task_response(response, start_time)

  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-Tripo\api\system.py", line 243, in _handle_task_response
    raise Exception(result)

```
## System Information
- **ComfyUI Version:** unknown
- **Arguments:** main.py
- **OS:** nt
- **Python Version:** 3.10.11 (tags/v3.10.11:7d4cc5a, Apr  5 2023, 00:38:17) [MSC v.1929 64 bit (AMD64)]
- **Embedded Python:** false
- **PyTorch Version:** 2.5.0.dev20240815+cu124
## Devices

- **Name:** cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
  - **Type:** cuda
  - **VRAM Total:** 25756565504
  - **VRAM Free:** 24110956544
  - **Torch VRAM Total:** 0
  - **Torch VRAM Free:** 0

## Logs
```
2024-10-31 13:52:45,525 - root - INFO - Total VRAM 24563 MB, total RAM 49031 MB
2024-10-31 13:52:45,526 - root - INFO - pytorch version: 2.5.0.dev20240815+cu124
2024-10-31 13:52:45,531 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-31 13:52:45,532 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-10-31 13:52:47,514 - root - INFO - Using pytorch cross attention
2024-10-31 13:52:49,818 - root - INFO - [Prompt Server] web root: F:\Ai\ComfyUI\web
2024-10-31 13:52:49,822 - root - INFO - Adding extra search path checkpoints O:\SDXL\stable-diffusion-webui\models\Stable-diffusion\
2024-10-31 13:52:49,826 - root - INFO - Adding extra search path configs E:\SD\stable-diffusion-webui\models\Stable-diffusion\
2024-10-31 13:52:49,831 - root - INFO - Adding extra search path vae O:\SDXL\stable-diffusion-webui\models\VAE\
2024-10-31 13:52:49,835 - root - INFO - Adding extra search path vae F:\Ai\ComfyUI_windows_portable\ComfyUI\models\vae\
2024-10-31 13:52:49,835 - root - INFO - Adding extra search path unet F:\Ai\ComfyUI_windows_portable\ComfyUI\models\unet\
2024-10-31 13:52:49,842 - root - INFO - Adding extra search path clip F:\Ai\ComfyUI_windows_portable\ComfyUI\models\clip\
2024-10-31 13:52:49,843 - root - INFO - Adding extra search path loras path/to/stable-diffusion-webui/models/Lora
2024-10-31 13:52:49,848 - root - INFO - Adding extra search path loras path/to/stable-diffusion-webui/models/LyCORIS
2024-10-31 13:52:49,854 - root - INFO - Adding extra search path loras O:\SDXL\stable-diffusion-webui\models\Lora\
2024-10-31 13:52:49,854 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/ESRGAN
2024-10-31 13:52:49,860 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/RealESRGAN
2024-10-31 13:52:49,866 - root - INFO - Adding extra search path upscale_models path/to/stable-diffusion-webui/models/SwinIR
2024-10-31 13:52:49,870 - root - INFO - Adding extra search path embeddings path/to/stable-diffusion-webui/embeddings
2024-10-31 13:52:49,875 - root - INFO - Adding extra search path hypernetworks path/to/stable-diffusion-webui/models/hypernetworks
2024-10-31 13:52:49,879 - root - INFO - Adding extra search path controlnet E:\SD\stable-diffusion-webui\extensions\sd-webui-controlnet\models\
2024-10-31 13:52:53,531 - ComfyUI-CogVideoXWrapper.custom_cogvideox_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-31 13:52:53,553 - ComfyUI-CogVideoXWrapper.cogvideox_fun.transformer_3d - INFO - sageattn not found, using sdpa
2024-10-31 13:52:53,556 - ComfyUI-CogVideoXWrapper.cogvideox_fun.fun_pab_transformer_3d - INFO - sageattn not found, using sdpa
2024-10-31 13:52:54,451 - root - INFO - Total VRAM 24563 MB, total RAM 49031 MB
2024-10-31 13:52:54,452 - root - INFO - pytorch version: 2.5.0.dev20240815+cu124
2024-10-31 13:52:54,458 - root - INFO - Set vram state to: NORMAL_VRAM
2024-10-31 13:52:54,461 - root - INFO - Device: cuda:0 NVIDIA GeForce RTX 4090 : cudaMallocAsync
2024-10-31 13:52:56,671 - root - WARNING - Traceback (most recent call last):
  File "F:\Ai\ComfyUI\nodes.py", line 2007, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-IP_LAP\__init__.py", line 1, in <module>
    from .nodes import IP_LAP,LoadVideo,PreViewVideo,CombineAudioVideo
  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-IP_LAP\nodes.py", line 10, in <module>
    from .ip_lap.inference import IP_LAP_infer
  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-IP_LAP\ip_lap\inference.py", line 7, in <module>
    from .face_mask import FaceMask
  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-IP_LAP\ip_lap\face_mask.py", line 5, in <module>
    from basicsr.utils.download_util import load_file_from_url
  File "F:\Ai\ComfyUI\venv\lib\site-packages\basicsr\__init__.py", line 4, in <module>
    from .data import *
  File "F:\Ai\ComfyUI\venv\lib\site-packages\basicsr\data\__init__.py", line 22, in <module>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "F:\Ai\ComfyUI\venv\lib\site-packages\basicsr\data\__init__.py", line 22, in <listcomp>
    _dataset_modules = [importlib.import_module(f'basicsr.data.{file_name}') for file_name in dataset_filenames]
  File "C:\Users\Ryzen_Reaper\AppData\Local\Programs\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "F:\Ai\ComfyUI\venv\lib\site-packages\basicsr\data\realesrgan_dataset.py", line 11, in <module>
    from basicsr.data.degradations import circular_lowpass_kernel, random_mixed_kernels
  File "F:\Ai\ComfyUI\venv\lib\site-packages\basicsr\data\degradations.py", line 8, in <module>
    from torchvision.transforms.functional_tensor import rgb_to_grayscale
ModuleNotFoundError: No module named 'torchvision.transforms.functional_tensor'

2024-10-31 13:52:56,672 - root - WARNING - Cannot import F:\Ai\ComfyUI\custom_nodes\ComfyUI-IP_LAP module for custom nodes: No module named 'torchvision.transforms.functional_tensor'
2024-10-31 13:52:59,151 - py.warnings - WARNING - F:\Ai\ComfyUI\custom_nodes\ComfyUI-segment-anything-2\sam2\modeling\sam\transformer.py:20: UserWarning: Flash Attention is disabled as it requires a GPU with Ampere (8.0) CUDA capability.
  OLD_GPU, USE_FLASH_ATTN, MATH_KERNEL_ON = get_sdpa_settings()

2024-10-31 13:53:03,831 - root - INFO - 
Import times for custom nodes:
2024-10-31 13:53:03,831 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\cg-use-everywhere
2024-10-31 13:53:03,833 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI_Noise
2024-10-31 13:53:03,833 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-GlifNodes
2024-10-31 13:53:03,833 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-YOLO
2024-10-31 13:53:03,834 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI_IPAdapter_plus
2024-10-31 13:53:03,834 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\stability-ComfyUI-nodes
2024-10-31 13:53:03,834 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Dickson-Nodes
2024-10-31 13:53:03,835 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-VideoHelperSuite
2024-10-31 13:53:03,836 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\cg-noisetools
2024-10-31 13:53:03,837 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-WD14-Tagger
2024-10-31 13:53:03,837 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\websocket_image_save.py
2024-10-31 13:53:03,838 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\comfyui_controlnet_aux
2024-10-31 13:53:03,838 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-SuperBeasts
2024-10-31 13:53:03,838 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Tripo
2024-10-31 13:53:03,839 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\DJZ-Nodes
2024-10-31 13:53:03,839 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyMath
2024-10-31 13:53:03,840 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\comfyui-various
2024-10-31 13:53:03,840 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Custom-Scripts
2024-10-31 13:53:03,840 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-post-processing-nodes
2024-10-31 13:53:03,841 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\comfyui_segment_anything
2024-10-31 13:53:03,841 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI_essentials
2024-10-31 13:53:03,842 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Manager
2024-10-31 13:53:03,842 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\comfy-image-saver
2024-10-31 13:53:03,842 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\virtuoso-nodes
2024-10-31 13:53:03,843 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Florence2
2024-10-31 13:53:03,843 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Frame-Interpolation
2024-10-31 13:53:03,843 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Advanced-ControlNet
2024-10-31 13:53:03,844 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-KJNodes
2024-10-31 13:53:03,844 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI_UltimateSDUpscale
2024-10-31 13:53:03,845 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Impact-Pack
2024-10-31 13:53:03,845 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\x-flux-comfyui
2024-10-31 13:53:03,845 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-GGUF
2024-10-31 13:53:03,846 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-segment-anything-2
2024-10-31 13:53:03,846 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-MochiWrapper
2024-10-31 13:53:03,846 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\rgthree-comfy
2024-10-31 13:53:03,847 - root - INFO -    0.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-AnimateDiff-Evolved
2024-10-31 13:53:03,847 - root - INFO -    0.1 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI_Comfyroll_CustomNodes
2024-10-31 13:53:03,847 - root - INFO -    0.1 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-IC-Light
2024-10-31 13:53:03,848 - root - INFO -    0.1 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI_bitsandbytes_NF4
2024-10-31 13:53:03,848 - root - INFO -    0.1 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI_smZNodes
2024-10-31 13:53:03,848 - root - INFO -    0.2 seconds: F:\Ai\ComfyUI\custom_nodes\comfy_mtb
2024-10-31 13:53:03,849 - root - INFO -    0.2 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Easy-Use
2024-10-31 13:53:03,849 - root - INFO -    0.2 seconds: F:\Ai\ComfyUI\custom_nodes\comfyui-tensorops
2024-10-31 13:53:03,850 - root - INFO -    0.5 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-SAM2
2024-10-31 13:53:03,851 - root - INFO -    0.6 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Crystools
2024-10-31 13:53:03,853 - root - INFO -    0.6 seconds: F:\Ai\ComfyUI\custom_nodes\comfyui-propost
2024-10-31 13:53:03,854 - root - INFO -    0.6 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-CogVideoXWrapper
2024-10-31 13:53:03,854 - root - INFO -    0.7 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Anyline
2024-10-31 13:53:03,854 - root - INFO -    0.9 seconds (IMPORT FAILED): F:\Ai\ComfyUI\custom_nodes\ComfyUI-IP_LAP
2024-10-31 13:53:03,855 - root - INFO -    1.0 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-SUPIR
2024-10-31 13:53:03,855 - root - INFO -    1.2 seconds: F:\Ai\ComfyUI\custom_nodes\comfyui-art-venture
2024-10-31 13:53:03,856 - root - INFO -    1.2 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-Image-Filters
2024-10-31 13:53:03,856 - root - INFO -    1.3 seconds: F:\Ai\ComfyUI\custom_nodes\ComfyUI-PyramidFlowWrapper
2024-10-31 13:53:03,857 - root - INFO -    2.9 seconds: F:\Ai\ComfyUI\custom_nodes\was-node-suite-comfyui
2024-10-31 13:53:03,857 - root - INFO - 
2024-10-31 13:53:03,882 - root - INFO - Starting server

2024-10-31 13:53:03,883 - root - INFO - To see the GUI go to: http://127.0.0.1:8188
2024-10-31 13:53:06,330 - root - INFO - got prompt
2024-10-31 13:54:35,465 - root - ERROR - !!! Exception during processing !!! An error occurred: 
2024-10-31 13:54:35,473 - root - ERROR - Traceback (most recent call last):
  File "F:\Ai\ComfyUI\execution.py", line 323, in execute
    output_data, output_ui, has_subgraph = get_output_data(obj, input_data_all, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\Ai\ComfyUI\execution.py", line 198, in get_output_data
    return_values = _map_node_over_list(obj, input_data_all, obj.FUNCTION, allow_interrupt=True, execution_block_cb=execution_block_cb, pre_execute_cb=pre_execute_cb)
  File "F:\Ai\ComfyUI\execution.py", line 169, in _map_node_over_list
    process_inputs(input_dict, i)
  File "F:\Ai\ComfyUI\execution.py", line 158, in process_inputs
    results.append(getattr(obj, func)(**inputs))
  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-Tripo\__init__.py", line 91, in generate_mesh
    result = api.image_to_3d(image_name, model_version, model_seed, texture_seed)
  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-Tripo\api\system.py", line 114, in image_to_3d
    return self._handle_task_response(response, start_time)
  File "F:\Ai\ComfyUI\custom_nodes\ComfyUI-Tripo\api\system.py", line 243, in _handle_task_response
    raise Exception(result)
Exception: An error occurred: 

2024-10-31 13:54:35,475 - root - INFO - Prompt executed in 89.09 seconds
2024-10-31 13:54:35,818 - asyncio - ERROR - Task exception was never retrieved
future: <Task finished name='Task-45' coro=<RequestHandler.start() done, defined at F:\Ai\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py:487> exception=AssertionError()>
Traceback (most recent call last):
  File "F:\Ai\ComfyUI\venv\lib\site-packages\aiohttp\web_protocol.py", line 530, in start
    request = self._request_factory(message, payload, self, writer, handler)
  File "F:\Ai\ComfyUI\venv\lib\site-packages\aiohttp\web_app.py", line 479, in _make_request
    return _cls(
  File "F:\Ai\ComfyUI\venv\lib\site-packages\aiohttp\web_request.py", line 841, in __init__
    super().__init__(*args, **kwargs)
  File "F:\Ai\ComfyUI\venv\lib\site-packages\aiohttp\web_request.py", line 196, in __init__
    assert transport is not None
AssertionError
2024-10-31 13:54:35,908 - root - WARNING - Failed to get ComfyUI version: Command '['git', 'describe', '--tags']' returned non-zero exit status 128.
```
## Attached Workflow
Please make sure that workflow does not contain any sensitive information such as API keys or passwords.
```
{"last_node_id":15,"last_link_id":12,"nodes":[{"id":7,"type":"LoadImage","pos":{"0":1068,"1":780},"size":{"0":313.6480407714844,"1":434.7273254394531},"flags":{},"order":0,"mode":0,"inputs":[],"outputs":[{"name":"IMAGE","type":"IMAGE","links":[8],"slot_index":0,"shape":3},{"name":"MASK","type":"MASK","links":null,"shape":3}],"properties":{"Node name for S&R":"LoadImage"},"widgets_values":["pasted/image (69).png","image"]},{"id":10,"type":"TripoGLBViewer","pos":{"0":2006,"1":775},"size":[600,500],"flags":{},"order":2,"mode":0,"inputs":[{"name":"mesh","type":"MESH","link":9,"slot_index":0}],"outputs":[],"properties":{"Node name for S&R":"TripoGLBViewer"},"widgets_values":[null]},{"id":9,"type":"TripoAPIDraft","pos":{"0":1519,"1":784},"size":[329.66668701171875,441.7777786254883],"flags":{},"order":1,"mode":0,"inputs":[{"name":"image","type":"IMAGE","link":8,"slot_index":0,"shape":7},{"name":"image_lr","type":"IMAGE","link":null,"shape":7},{"name":"image_back","type":"IMAGE","link":null,"shape":7}],"outputs":[{"name":"MESH","type":"MESH","links":[9],"slot_index":0,"shape":3},{"name":"MODEL_TASK_ID","type":"MODEL_TASK_ID","links":[],"slot_index":1,"shape":3},{"name":"API_KEY","type":"API_KEY","links":null,"shape":3}],"properties":{"Node name for S&R":"TripoAPIDraft"},"widgets_values":["image_to_model","tsk_jYB9Y1UjGQR42gz4g_jj878FXWVGi39E9c2r4ATF_UK","a armchair red color.","LEFT",false,"v2.0-20240919",0,0,0]}],"links":[[8,7,0,9,0,"IMAGE"],[9,9,0,10,0,"MESH"]],"groups":[],"config":{},"extra":{"ds":{"scale":1,"offset":[-819.5556030273438,-560.2222290039062]}},"version":0.4}
```

## Additional Context
(Please add any additional context or steps to reproduce the error here)

**Comment by seed93** [comment]
Does it happen all the time?
